# Generated by Django 6.0.5 on 2026-06-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fitness_goal',
            field=models.CharField(choices=[('slim', 'Get Slim / Fat Loss'), ('gain', 'Gain Muscle / Hypertrophy'), ('maintain', 'Maintain Current Weight')], default='maintain', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, help_text='Height in centimeters (cm)', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight',
            field=models.FloatField(blank=True, help_text='Weight in kilograms (kg)', null=True),
        ),
    ]
