# Generated by Django 6.0.5 on 2026-06-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_age_userprofile_fitness_goal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activity_level',
            field=models.CharField(choices=[('sedentary', 'Little to no exercise'), ('light', 'Light exercise (1-3 days/week)'), ('moderate', 'Moderate exercise (3-5 days/week)'), ('active', 'Heavy exercise (6-7 days/week)')], default='sedentary', max_length=15),
        ),
    ]
