# Generated by Django 6.0.5 on 2026-06-16 09:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_date_of_birth_userprofile_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio_title',
            field=models.CharField(blank=True, default='Certified Fitness Coach', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experience_years',
            field=models.IntegerField(blank=True, default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_accepting_clients',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_capacity',
            field=models.IntegerField(blank=True, default=15, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialization',
            field=models.CharField(blank=True, choices=[('hypertrophy', 'Body Recomposition & Hypertrophy'), ('athletic', 'Athletic Performance & Conditioning'), ('mobility', 'Functional Mobility & Injury Rehab'), ('general', 'General Health & Weight Management')], default='general', max_length=20),
        ),
    ]
